CREATE TABLE IF NOT EXISTS `character_wallet_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `character_id` bigint(20) NOT NULL,
  `type_id` int(11) NOT NULL,
  `type_name` varchar(250) NOT NULL,
  `quantity` int(11) NOT NULL,
  `client_id` int(11) NOT NULL,
  `price` decimal(16,2) NOT NULL,
  `station_id` int(11) NOT NULL,
  `transaction_date_time` datetime NOT NULL,
  `transaction_type` varchar(50) NOT NULL,
  `station_name` varchar(100) NOT NULL,
  `client_name` varchar(100) NOT NULL,
  `transaction_for` varchar(50) NOT NULL,
  `transaction_id` bigint(20) NOT NULL,
  `cached_until` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `character_id` (`character_id`),
  KEY `type_id` (`type_id`),
  KEY `client_id` (`client_id`),
  KEY `transaction_id` (`transaction_id`),
  KEY `station_id` (`station_id`),
  KEY `cached_until` (`cached_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;