CREATE TABLE IF NOT EXISTS `forum_users` (
  `userid` int(10) NOT NULL,
  `username` varchar(200) NOT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `forum_users` (`userid`,`username`) VALUES (2,'GRD - Gromozeka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3,'GRD - MACTEP');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4,'GRD - Cav3men');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (6,'GRD - Air Comando');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (5,'TFFN - DENWIR');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (7,'GRD - Span1ard');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (10,'SDG - Morel');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12,'GRD - 6ecceHok');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15,'GRD - Degront');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (16,'GRD - Khump');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (17,'GRD - Evengard');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (18,'GRD - Okita Souji');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (19,'GRD - Bratik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (23,'GRD - Torpp');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (25,'GRD - Eksgumat0r');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (26,'ZET - Insomnious');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (27,'ZET - DeadlyDoze');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (30,'GRD - Trembler');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (38,'GRD - J Malkavian');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (40,'GRD - DeeGree');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (41,'GRD - babayaroo');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (42,'TFFN - PeaceDeath');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (47,'TFFN - XsadistX');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (49,'GRD - Millar Shout');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (53,'GRD - VedMed');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (54,'SDG - RedUnion');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (58,'GRD - Hunterzzz');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (65,'SDG - herr Cooper');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (66,'GRD - TITANIK');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (67,'SDG - Ruthless Murderer');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (71,'GRD - Elianor84');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (83,'GRD - cosm0s');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (84,'GRD - wise kaa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (91,'SDG - Tarkween');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (93,'GRD - MPAK06EC');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (94,'PREET - Casgod');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (97,'GRD - Terrytory');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (102,'PREET - Cruentus Lupus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (105,'GRD - Futsen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (126,'TFFN - ScoRRax');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (226,'UKR - Mak Lesser');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (106,'ZET - BallBess');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (113,'TFFN - IIITyIIIa KyTyIIIa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (114,'SDG - Fenix UA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (115,'TFFN - Kisl\'y Monk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (118,'ZET - MiNM');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (120,'GRD - NoOne Seeko');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (220,'GRD - PhOeN1x2k');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (225,'UKR - Zhyga');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (132,'SDG - Zabiaka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (136,'GRD - sig orsk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (137,'ZET - cyberelk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (139,'GRD - Feuer Frei');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (140,'TFFN - Xellos Milennium');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (146,'TFFN - Cavtrooper');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (149,'TFFN - Bars');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (157,'GRD - Executer SV');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (159,'REAL - Ginbread');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (222,'UKR - Denter Bondar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (172,'TFFN - Zidrik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (187,'GRD - REVERSE777');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (188,'GRD - Hostum');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (191,'ZET - CTPEJ1Ok');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (192,'SDG - Ozzikru');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (207,'SDG - DirtyAfro');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (229,'UKR - Renich');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (232,'UKR - Mau Gli');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (234,'UKR - K 004');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (235,'UKR - Xxela');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (238,'UKR - DomoBou');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (239,'UKR - Star Archer');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14812,'TFFN - Cerberus II');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (244,'UKR - Denis X');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (245,'UKR - CePoBoDoPoD');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (249,'UKR - Viktor Banderovec');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (250,'UKR - Tarun');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (255,'UKR - Ch1');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (256,'UKR - Virm');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (259,'UKR - Steel Felix');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (262,'UKR - DarkTex');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (267,'UKR - Timerlan');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (271,'UKR - Fan Kezyr');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (272,'UKR - ASA VIKING');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (284,'TFFN - ArchE');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (286,'UKR - Thart');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (288,'UKR - COSinUSE');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (291,'SDG - rsa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (295,'ZeT - Massly');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1313,'NOFT - Narrin Sheridan');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (323,'ZET - John Kriden');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (334,'UKR - Sherbinka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (335,'GRD - Zloj MaNGooST');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (387,'TFFN - capGreen76');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (395,'GRD - AxTuBURN');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (399,'ZET - Sallyvan');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (402,'UKR - S Bandera');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (406,'SPARF - Jupiter Antonius');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (431,'NOFT - Gans71');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (481,'U.K.C - Dgehat');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (492,'SDG - Sunsayeach');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (493,'SDG - xRepin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1048,'TFFN - Cranb');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (499,'TFFN - Raiderovi4');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (516,'SDG - Bishop orsk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (520,'UKR - Galichian');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12076,'MED - Sleit');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (647,'GRD - UAxLelik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (770,'UKR - Jilencov');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (688,'GRD - Angva');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (714,'TFFN - Gera W');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (724,'UKR - WARonin DS1980');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1071,'GRD - Anomiel');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (788,'NOFT - Sazir');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (801,'ZET - Tronoxx');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (851,'NOFT - Raziel001');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (853,'NOFT - Padliuka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (856,'NOFT - Queenofsun');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1667,'TFFN - Ke1th Fl1nt');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (858,'NOFT - Entetri');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (860,'NOFT - pryDrik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (864,'NOFT - cl0P');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (900,'UKR - Ergoliolgolissa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14939,'REALA - Omen malum');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (937,'NOFT - Yxvat');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (953,'TFFN - H Andrew');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (960,'TFFN - Another Night');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1053,'NOFT - Wisard');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1084,'GRD - XCloudimus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1088,'UKR - kilka starry');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12386,'NOFT - Jedif');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1093,'ZET - JohnKriden Son');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1202,'TFFN - Ammersau');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1199,'REAL - RPBANDEP');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1161,'UKR - Spun4eg');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1208,'TFFN - Observer Vyacheslav');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1212,'UKR - BoiHif');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1231,'NOFT - Erdenet');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1254,'GRD - Zeeroth');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1299,'REAL - Vladim ir');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1338,'GRD - ZaaR13');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1337,'TFFN - gg99');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12117,'REAL - XUrann');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1366,'TFFN - Jenias');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1383,'HNES - Sap hazar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1417,'NOFT - KHR3b TbMbI');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1426,'TFFN - FieryRain');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1431,'TFFN - Aseta kpi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1441,'GRD - Korshun');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12531,'HARD - PIZUNDA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12536,'PREET - Je5ter Darwin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1479,'TFFN - Evgeniy Gusev');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1482,'TFFN - Hirreling');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1485,'TFFN - AlertForce');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1491,'TFFN - Valerian Irenicus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1496,'UKR - IxJOKERxI');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1497,'TFFN - PaddyMayne');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1514,'UKR - SirRalph');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1578,'TFFN - Viktor Aleksin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1533,'TFFN - Ash2h');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1537,'TFFN - zeleniy777');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1547,'TFFN - ErioocL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1672,'SDG - Linkanoid');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1575,'UKR - Alex Medvecky');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1577,'TFFN - Okapist');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1581,'TFFN - DeamoNKI');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1585,'HNES - Leprasac');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1592,'TFFN - Staffa Terma');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1656,'SDG - Uvis');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (1662,'TFFN - Hisara');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12004,'TFFN - rommario69');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12534,'HNES - Yazri');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12524,'HNES - Gigemon Reverbiron');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12525,'HNES - Neiner');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3665,'UKR - Romkin LV');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3737,'TFFN - I Sam');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3793,'TFFN - Snake Darkscar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3805,'TFFN - CrichtonJ');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3840,'TFFN - True Nastr');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3972,'U.K.C - Andrzej Podeszwa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3973,'U.K.C - ZyDrA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3977,'U.K.C - Zion Ru');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (3993,'U.K.C - Well Man');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4021,'U.K.C - Ogneborec');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4024,'U.K.C - 58rusStrannikRoma');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12119,'med - Evgenyi Lepechin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4050,'TFFN - Ros0maha');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4065,'U.K.C - TEHb KOMETbl');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4092,'TFFN - C0linMcRae');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4123,'U.K.C - Levenson');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4203,'UKR - Marshal UA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (4341,'U.K.C - Sitri Kaet');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12572,'TFFN - antimiks');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (5592,'U.K.C - Nechupara');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12175,'NOFT - Savage77');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (5597,'U.K.C - Cordegelius');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (6048,'TFFN - lt Wargod');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (6087,'TFFN - Keeper1000');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12568,'TFFN - Small Pistol');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (6094,'TFFN - Commandor 042');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12520,'HNES - Andrew Pol');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12516,'TFFN - Fox Armored');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (9109,'PREET - Crystal2');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (9653,'TFFN - lilianzz');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (10534,'TFFN - Ster Ri36');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12574,'TFFN - Ron Catari');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11958,'TFFN - OCIPIC');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11965,'TFFN - Spurk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11964,'TFFN - MrTashi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11967,'TFFN - DarkChopa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11978,'TFFN - cmdr Daniel');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12528,'U.K.C - DP0H');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11997,'UKR - Tacid');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (11996,'TFFN - Maichle Garibaldi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12008,'TFFN - Butich');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12020,'TFFN - Vold 2');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12021,'TFFN - Asteris Trild');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12022,'TFFN - Vitaliy Arbosa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12176,'GRD - Darky am');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12338,'GRD - Angry Romko');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12056,'GRD - Ogucceu');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12111,'ZET - gleo602');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14580,'WING - 4eLioS');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12069,'MED - Pretorik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12074,'MED - Crimson Rover');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14457,'STZRU - D0brik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12077,'MED - Dorsai Ral');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12078,'MED - elita force');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12080,'MED - Yard Egivand');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12081,'TFFN - anonimcheggg');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12082,'SPARF - Instate');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12084,'SPARF - Tuhiro');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12523,'HNES - Koros Baklanov');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12101,'SPARF - Gnuzdyanka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12106,'HARD - Bitterfly');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12118,'TFFN - Eva Brutt');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12145,'HARD - expansus kapai');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12125,'UKR - DJ Sopilka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12129,'TFFN - AvrilLavi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12131,'TFFN - Corsa Cor');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12133,'TFFN - Vinsent Moon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12138,'TFFN - Vo Ron');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12144,'HARD - vizmar Estemaire');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12142,'HARD - Staen Serov');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12143,'HARD - Babyface UK');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12173,'NOFT - Artanetc');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12147,'U.K.C - Myk Taison');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12152,'TFFN - Billy Kremator');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12165,'SPARF - Mac Sim');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12168,'GRD - Crompic');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12172,'HARD - DYAK Viliana');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12174,'MED - Basjak');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12251,'WING - Vlata');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12183,'GRD - Xano Mora');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12186,'TFFN - Dima Troy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12187,'TFFN - claus7');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12193,'TFFN - Gadmat');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12197,'TFFN - Zu Lus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12199,'GRD - Serger');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12203,'U.K.C - PilotNick');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12207,'TFFN - Dankes');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12208,'TFFN - JekyBoy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12219,'HARD - Andrey T');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12224,'WING - Dnole');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12231,'GRD - Midnight Exyos');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12240,'WING - sla16');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12250,'TFFN - Grom Quaker');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12253,'TFFN - d3ZoRg Chipri');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12271,'GRD - Cyanide Egnald');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12283,'WING - ALEX SHEVCHENKO');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12286,'WING - Vasyalisk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12301,'TFFN - de\'Sad');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12306,'TFFN - Terens Cassidy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12307,'TFFN - Kim Toretos');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12308,'TFFN - Razy-EL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12310,'TFFN - DARK SERG');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12315,'TFFN - UPOKE3');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12317,'REAL - Hithui');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12329,'HNES - DAUBEP');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12343,'ZET - SigaretkO');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12357,'GRD - Blad02');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12487,'TFFN - El\'Stratus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12427,'SDG - Mak 82');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12460,'GRD - Ket Hunt');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12481,'TFFN - SoulEater Star');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12482,'TFFN - Killer Mo');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12587,'U.K.C - Aleksey Chelien');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12590,'HARD - Dmitriy Vladimirovch');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12611,'HNES - Zufik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12623,'HNES - Friend Eto');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12624,'HNES - Naari Aivoras');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12647,'REAL - Nolg');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12652,'REAL - Murtanu Mabata');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12653,'REAL - Vikky Fox');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12657,'TFFN - IIGNOMEII');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12660,'REAL - BATIAJ');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12663,'HNES - Cyber Knightss');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12666,'NRAEL - DART DOBER');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12668,'NRAEL - Well Man');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12674,'HNES - Mick Shihari');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12680,'REAL - 14Lexa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12694,'TSFN - VBA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12699,'REAL - Cesar de Borja');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12703,'HNES - Gregor2003 Tadevosyan');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12706,'Wing - Alail Serma');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12712,'WING - Aikid0ka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12754,'UKR - DishIF');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12766,'UKR - bluechimera');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12829,'REAL - Melira Alabel');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12832,'TFFN - Dragons Master');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12833,'TFFN - ASTARTES UMANGIAR');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12834,'TFFN - BaraBa4chKA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12838,'TFFN - Alail Serma');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12850,'TFFN - deniAce');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12856,'REAL - Ragnar Morrel');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12866,'TFFN - Korsar-007');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12882,'REAL - Gnoll Spellhowler');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12901,'U.K.C - Norfinn');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12903,'U.K.C - FLOut MASTER');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12930,'HNES - Veil Eto');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12954,'REAL - Samanta Carterr');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12972,'RUSH - Shadow Falcon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12974,'RUSH - LegaRoSSs');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12976,'RUSH - MaceWindow');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12978,'RUSH - Darth Ilya');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12979,'RUSH - Fantic10');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12980,'RUSH - ArSik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12991,'RUSH - IgorK');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12983,'RUSH - Myshyakovich Tadaruwa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12984,'RUSH - Zakko Mernher');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12985,'RUSH - baagpus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12986,'RUSH - prachy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12987,'RUSH - Gatling Autocannon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12988,'RUSH - Morzius');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12989,'RUSH - MrDeputat');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12994,'RUSH - QROQUS');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12997,'RUSH - Xitriy Bes');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (12998,'RUSH - Eyne Stlaker');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13000,'RUSH - Traktorisd');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13002,'RUSH - RedScorpion777');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13004,'RUSH - RUSBarab');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13005,'RUSH - AlexPAN');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13009,'RUSH - Lady Fee');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13010,'RUSH - Outreach');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13012,'RUSH - CTpeJIEu');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13177,'HNES - Senya CA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13034,'REAL - Al Tan');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13057,'REAL - First Snow');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13060,'UKR - Vadim Lisa');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13061,'RUSH - MAXACAMATMAH');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13073,'TFFN - OddinV');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13078,'RUSH - Serafim Flamingise');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13088,'JDT - Kaifus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13137,'RUSH - 4mydreams');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13383,'STG - Lt Erl');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13155,'RuSH - WillDeOneHalf');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13159,'HNES - Darna Okaski');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13166,'SW - Agatsum');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13168,'RUSH - DonAntonio');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13169,'HNES - fatshamvey gordon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13173,'HNES - Veter Thanderstorm');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13176,'REALA - Samanta Carterr');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13195,'HNES - SnansY');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13196,'REAL - Min001');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13203,'MED - razvoz');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13205,'TFFN - VBA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13418,'TFFN - Plodding');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13233,'GRD - ALIEN GTR');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13234,'GRD - AHAPXUCT');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13248,'REALA - MsHappy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13259,'TFFN - SYS0');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13261,'REAL - Marius Hinken');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13265,'TFFN - Horgi Werewolf');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13291,'HNES - skull ivanovi4');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13317,'RUSH - Hexplorer I');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13339,'wing - Mihael Molou');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13320,'TFFN - Replikonn en Marland');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13323,'TFFN - Esajah Ajahsiree');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13348,'RUSH - Ferzenand');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13388,'STG - Imperror Togosaki');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13355,'REALA - BATIAJ');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13372,'WING - Tormoz Torm');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13376,'TFFN - ARH ANGELks');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13407,'REAL - sh00tist');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13381,'STG - DarkPaint666');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13387,'STG - MasL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13392,'STG - Alexey Deathperado');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13393,'STG - Miheev san');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13394,'REALA - DeepChord');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13423,'STG - StrannikNebes');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13454,'REALA - Maksim Bespalko');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13457,'REAL - gena brat');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13472,'TFFN - K0bal');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13474,'RUSH - Ivan Tkanschuk');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13509,'WING - eshkin kott');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13483,'REALA - MaximWasp');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13484,'TFFN - Eugen Kidd');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13487,'REAL - Rimfus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13505,'WING - Alex Lenin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13530,'UKR - Duke Caliostro');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13541,'REALA - Tophok Acme');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14034,'REAL - Colin Yield');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13565,'HNES - Nik Azgard');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13553,'NOFT - urko10');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13555,'MIE - texnl');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13561,'REAL - Alagorn Resko');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13574,'UKR - SmithJV');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13581,'STG - oneapple oneapple');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13584,'PREET - abarsh');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14920,'KROT - Tosh Landmark');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13755,'REDGU - Denspleed');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13619,'REALA - Veris Alland');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13661,'TFFN - Barchetto VIP');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13787,'TFFN - Ja\'li');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13675,'HNES - Delnark');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14845,'REALA - William Gottentog');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14442,'REALA - Mario Hendar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13686,'TSFN - Ivan Anisiforow');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13693,'RUSH - thePaasHaas');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14834,'MIE - Pluhskin dedja');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13717,'T-APA - AK 101');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13730,'T-APA - Naar I\'nir');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13724,'T-APA - Blayzer Hacker');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13725,'T-APA - Ortega Stanwell');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13727,'T-APA - 5 STEEL RAT');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14779,'STZRU - Machumb');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13731,'T-APA - Shamhun');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13744,'MED - Calipsia');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13740,'STZRU - AlexSniper');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13767,'RUSH - Mr Baenre');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13757,'REALA - NiaX Scandal');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13766,'REAL - Keltus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13771,'STZRU - neirofank');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13772,'STZRU - SergSniper');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13774,'T-APA - Anarhist DaNuNax');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13851,'MED - Alex Lenin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13825,'REALA - Artix Kupol');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13822,'UKR - Duka Nukem');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13838,'T-APA - Fernando Valdes');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14452,'STZRU - Qshar Green');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13853,'WING - Makc White');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13857,'TSFN - Aster Alar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13859,'REALA - Rapid RTRN');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13892,'RUSH - Insane Fire');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13863,'SPARF - velnes');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13867,'REALA - TETKA KOCMOHABTKA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14942,'REDGU - Daomir');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13871,'TFFN - Irina 6185');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13875,'TFFN - Agvara');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13876,'NOFT - Hawk Flying');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13877,'NOFT - EK3EKyTOP');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14781,'REAL - Artix Kupol');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13882,'U.K.C - Emilka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13886,'REAL - Merhn Mernher');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14840,'REALA - Happy V');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14826,'REALA - Essonaby');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13893,'GRD - Savushka');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15028,'IBAH - BESOID');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13907,'REAL - Maksim Bespalko');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13914,'NRAEL - Jack Vong');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13915,'REAL - DeepChord');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14147,'TFFN - Past Fayer');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13918,'REAL - Veris Alland');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13960,'T-APA - Dmitry Tsar-i-Bog');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13936,'NOFT - Kaifus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14830,'REALA - nadjiklidabulu');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14804,'U.K.C - Rusalkin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13957,'REALA - Nienna Itinen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14807,'REALA - Dead Mazzai');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14009,'RUSH - NoiR X3');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13967,'UKR - Walop');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13969,'Wing - Auranin Enat');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13970,'REALA - Andrey Sanagurskyy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13986,'TFFN - LETUIN');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (13998,'MED - Babutto');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14003,'MED - Liskar Fehrnah');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14968,'RIBS - Subodai Han');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14029,'MED - deonis60');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14062,'STZRU - 6u4');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14039,'SPARF - alex2stars');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14043,'P.S. - pRossT');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14044,'TFFN - Mesenger wing');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14050,'REAL - Rapid RTRN');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14069,'PREET - Whiskey669');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14055,'REAL - NiaX Scandal');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14065,'MIE - Dmitry McGrey');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14066,'MIE - Peter Arkaral');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14067,'U.K.C - neirofank Orlenard');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14077,'WING - Arkasius Sonikus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14842,'HNES - Karrok Magn');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14153,'REALA - Lira Metesur');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14110,'TFFN - Alexey PROTOSS');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14175,'T-APA - CTPAHIK P');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14283,'REAL - Maxac Charante');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14132,'TFFN - Lupold Hakaari');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14141,'MED - Ruben Roff');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14139,'P.S - Azoh Atavuli');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14151,'REAL - TETKA KOCMOHABTKA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14168,'MED - Celever');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14162,'NOFT - Vlad Grizzly');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14756,'AGS - cr Timon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14182,'TFFN - EvlEye O\'Bazz');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14187,'TFFN - JIexA bmw');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14195,'MED - Aaron Goldman');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15017,'RIBS - Grobovschik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14202,'AGS - all72');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14208,'T-APA - 4ux-nblx');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14821,'TSFN - Pontiac TLOM');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14226,'REAL - Ktulchu Glatze');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14332,'TFFN - Edera Raine');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14248,'WING - Notorious T');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14846,'TSFN - Lexx Beddelver');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14481,'TFFN - Saint Fierce');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14325,'REALA - Fluke Network');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14273,'WING - 11fox');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14284,'REALA - Alagorn Resko');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14291,'WING - Serg Uisen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14301,'REALA - Phyrexian man');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14324,'REAL - MaxPhela');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14327,'UKR - Kotofey Ivanich');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14333,'STG - Jess Claymore');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14335,'RUSH - Venzer Korabelnikov');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14340,'TFFN - Geserg');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14351,'RSSCP - 3vezdopad');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14353,'RSSCP - abrakadabra ivanov');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14359,'Rsscp - Uni Alfrir');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14355,'RSSCP - Yardek Plaude');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14362,'RSSCP - Mex Arran');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14363,'RSSCP - Silruin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14366,'RSSCP - Orlangure');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14365,'RSSCP - DLM');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14368,'RSSCP - killer sniper');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14372,'RSSCP - Kira Amatis');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14817,'REAL - actofnoobs');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14376,'WING - Suatkan Shabar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15027,'MIE - Bobdjak');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14827,'MIE - Slytrick');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14426,'REAL - Lira Metesur');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14385,'REALA - Olbert First');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14889,'UKR - Kormack Solir');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14799,'TFFN - Ballistik196');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14397,'TSFN - Chips Merkaba');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14809,'REAL - Tensor Coil');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14418,'T-APA - Dan Karter');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14797,'REALA - Longspace');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14425,'REAL - Silver Getsuga');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14429,'REAL - Iperoz');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14448,'T-APA - Mefodii Kirillovich');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14453,'TFFN - Limmer');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14794,'TSFN - Morgan Ironheart');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14458,'STZRU - BTR80');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14483,'RUSH - Moombahton');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14490,'RSSCP - LtSaimon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14525,'RSSCP - babayan zerg');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14528,'RSSCP - Exteris');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14529,'RSSCP - 6aPoH Demetr');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14531,'RSSCP - Sand Wraith');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14534,'REALA - Geralt Brinalle');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14540,'RSSCP - Akemi1');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14800,'REALA - Albert NHL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14543,'TFFN - xVKx');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14843,'HNES - Bohum');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14586,'REAL - Obsidian Dog');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14589,'Sparta - Vit Komar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14597,'TFFN - Smi1ee');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14600,'REAL - Nienna Itinen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14605,'TFFN - Speedball Dirkallente');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14607,'REALA - Antibiot');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14632,'Sparta - Viach Slavnei');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14635,'REALA - actofnoobs');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14841,'REAL - STELS KILL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14641,'.RuF. - Zer0s');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14645,'Red - Vohann Bezrodnyi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14652,'KROT - Podjog Saraev');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14660,'REAL - MestislavK');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14677,'RSSCP - Pazzesqo');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14672,'REALA - Stanislav Petrovich');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14738,'REALA - Xakim Lt');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14675,'U.K.C - Intara Fem');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14976,'REDGU - Pahic');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14678,'REDGU - xEvilHunteRx');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14709,'.RUF. - Nikita Novoselov');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14690,'U.K.C - Rim 7979');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14777,'TFFN - Bender Log');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14741,'MIE - Silenser Hashiur');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14798,'STZRU - Maxim Herzog');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14701,'WING - Omen malum');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14702,'KROT - serginss');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14706,'REAL - Fluke Network');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14711,'REAL - Bra hman');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14929,'HNES - Timophey Sergeevich');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14795,'REALA - Meiv Frye');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14722,'RSSCP - xKPECTOHOCELLx');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14724,'REALA - Tensor Coil');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14730,'MIE - Gedych');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14839,'REALA - Mylene Turunen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14755,'REAL - Stine Hakaari');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14761,'MED - Icehold');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14776,'TFFN - Nym\'Ra');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14766,'TFFN - Ignor Candid');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14767,'REALA - Jazeed');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14828,'AGS - Labean');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14784,'TFFN - MeerEgor');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14926,'UKR - Vincent Greed');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14786,'TFFN - Chips Merkaba');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14788,'REAL - Mario Hendar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14805,'RUSH - Rea Roy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14789,'MIE - Veresk Giv');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14792,'RSSCA - Lepilla');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14847,'REALA - Takka Welle');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14850,'REALA - Inquisitor Holy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14851,'REALA - b0ltik');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14852,'WING - Albert NHL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14855,'REAL - Longspace');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14856,'UKR - Meero Naj');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14857,'MIE - huko1');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14858,'REAL - Xakim Lt');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14859,'REAL - Geralt Brinalle');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14879,'P.S. - Bobkov Konstantin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14860,'REAL - VasekK');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14861,'MIE - Lord Brother Captain');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14863,'MIE - Magnetiks');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14871,'TSFN - Wesper Solette');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14877,'REALA - Mikko Johansen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14878,'P.S. - Mor Kahoudi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14881,'KROT - Buxop');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14882,'TFFN - AirWolf09');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14883,'REDGU - sergeant hunter');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14884,'REALA - Frosya Molou');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14887,'REDGU - Dmitri Demon');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14885,'REDGU - Notys');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14886,'REDGU - Filia Tacabus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14892,'REDGU - AlexG G');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14894,'REDGU - Xiaozhen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14895,'RIBS - Hireling Hunter');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14896,'RIBS - Zelendub');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14897,'RIBS - Sheldin89');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14898,'RIBS - Alex Shtirlic');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14900,'RIBS - Max BC');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14901,'RIBS - Lindjin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14902,'RIBS - Kotofeya');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14903,'RIBS - Brandser');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14904,'RIBS - Khokhlushka UA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14918,'RIBS - Sir Pantagruelle');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14906,'RIBS - Mikey Poonanny');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14907,'REDGU - misye N shedevr');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14908,'RIBS - SIMPLE STEP');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14909,'RIBS - Kagyr Maur');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14910,'RIBS - Ururh');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14911,'RIBS - Silo Log');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14912,'RIBS - Stahan0f');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14913,'REDGU - stopard');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14914,'RIBS - CapitanPas');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14915,'RIBS - Shai Khulud');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14917,'MIE - Sergeii Caldari');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14919,'HNES - RiVGoSH');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14923,'RIBS - Serge PSV');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14927,'RSSCA - Yuriy galkinn');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14928,'RIBS - WORON RUS-23');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14930,'REALA - Sakura Ururu');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14931,'REDGU - BBerdan');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14960,'MED - ValeraVvV');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14954,'REDGU - Nikola Freedom');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14941,'REAL - nadjiklidabulu');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15055,'TACOM - Vejres');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14934,'RSSCP - Sieve Yazria');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14935,'NOFT - ARa DL');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14947,'REDGU - Aleronius');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14944,'RIBS - William Erkkinen');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14945,'REALA - Evil Oblivion');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14946,'HNES - Froll Audene');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14948,'REDGU - Scott Backer');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14950,'TSFN - Kibajaz Spacewalker');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14951,'NOFT - Timur 3EMA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14952,'REALA - Useless King');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14958,'RIBS - El\'minster');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14957,'-TFN- - Alex Povar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14959,'RIBS - Denver33rus');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14965,'MED - Magnetiks');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15037,'REALA - M1dnight');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14979,'REAL - Happy V');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14967,'TFFN - Flame Predator');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14969,'REALA - Daedalus Yumeno Metion');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14972,'TEAMH - Pahic');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14990,'REAL - Meiv Frye');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14971,'REAL - Mupuad');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14973,'REALA - Alik Killai');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14975,'RIBS - Turmant');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14980,'REAL - Inquisitor Holy');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14981,'REAL - Takka Welle');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14982,'REAL - Dead Mazzai');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14987,'REAL - kros danisfor');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14996,'WING - lightning0314');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (14999,'WING - Variolla');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15004,'REAL - Phyrexian man');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15006,'WING - gnommer NF Crusader');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15009,'WING - KOTE Tokila');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15010,'WING - TONI WONG');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15013,'RIBS - Angel Guard1an');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15014,'REALA - Demos Lig');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15026,'WING - Alex Taylor');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15015,'TFFN - GnevTYT');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15018,'MIE - Dread Mopo3');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15021,'RIBS - Kirs Kuvakei');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15022,'REAL - Intrasiclette');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15023,'MIE - eXiser');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15031,'REALA - Ailerum');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15033,'RIBS - Quariti Hinken');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15042,'WING - Aleksandr Bash');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15039,'REDGU - Mstislaw');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15040,'RIBS - Nebelunga252');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15041,'MED - Slytrick');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15043,'KHORN - MaximusDeci Meridi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15044,'Wing - Uki Kortana');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15045,'WING - Tai Irbiss');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15046,'TACOM - Kosily');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15047,'TACOM - Nepbuuhaxe');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15049,'TACOM - 72AG Goosf');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15050,'TACOM - Vohann Bezrodnyi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15051,'TACOM - SERJ GENT');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15053,'TACOM - MegaAdmiral');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15054,'RIBS - Vremennoi Omaristos');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15057,'K.HOR - Soldate');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15058,'REDGU - Donatello Bo');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15059,'AGS - Hamidashi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15060,'RIBS - KOTE Tokila');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15061,'WING - SS20 SATANA');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15062,'TACOM - xStealthx xbomberx');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15065,'REAL - William Gottentog');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15064,'NOFT - Ms Ragno');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15066,'RIBS - Antifrizz');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15068,'WING - Vlad Mol');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15070,'MIE - Ber Ameno');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15072,'MIE - Sonia Silent');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15073,'AGS - RealBlood Dallocort');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15074,'AGS - Mogilnyi');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15075,'RSSCA - Den4ik Miromme');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15076,'REALA - Q-Chast1c');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15077,'RIBS - Toni Wong');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15078,'MIE - Tina Atruin');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15081,'WING - Vegon Mega');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15087,'STZRU - Alex Povar');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15082,'HNES - Alexander Demonis');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15084,'MIE - Demure Tabris');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15085,'MIE - EdoXeplion');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15088,'MED - Whitebear77');
INSERT INTO `forum_users` (`userid`,`username`) VALUES (15090,'REALA - Evgeniy Snayper');
