-- DROP TABLE `industry_jobs`;
CREATE TABLE IF NOT EXISTS `industry_jobs` (
  `job_id` bigint(20) NOT NULL,
  `corporation_id` bigint(20) NULL,
  `installer_id`   bigint(20) NOT NULL,
  `installer_name`   varchar(150) NOT NULL,
  `facility_id` bigint(20) NOT NULL,
  `solar_system_id` bigint(20) NOT NULL,
  `solar_system_name` varchar(100) NOT NULL,
  `station_id` bigint(20) NOT NULL,
  `activity_id` int(11) NOT NULL,
  `blueprint_id` bigint(20) NOT NULL,
  `blueprint_type_id` int(11) NOT NULL,
  `blueprint_type_name` varchar(200) NOT NULL,
  `blueprint_location_id` bigint(20) NOT NULL,
  `output_location_id` bigint(20) NOT NULL,
  `runs` int(11) NOT NULL,
  `cost` double(20,2) NOT NULL,
  `licensed_runs` int(11) NOT NULL,
  `probability` double(20,2) NOT NULL,
  `product_type_id` int(11) NOT NULL,
  `product_type_name` varchar(200) NOT NULL,
  `status` int(11) NOT NULL,
  `time_in_seconds` int(11) NOT NULL,
  `start_date` datetime NOT NULL,
  `end_date` datetime NOT NULL,
  `pause_date` datetime NOT NULL,
  `completed_date` datetime NOT NULL,
  `completed_character_id` bigint(20) NOT NULL,
  `successful_runs` int(11) NOT NULL,
  `cached_until` datetime NOT NULL,
  PRIMARY KEY (`job_id`),
  KEY `corporation_id`  (`corporation_id`),
  KEY `installer_id` (`installer_id`),
  KEY `facility_id` (`facility_id`),
  KEY `solar_system_id`  (`solar_system_id`),
  KEY `station_id` (`station_id`),
  KEY `activity_id` (`activity_id`),
  KEY `blueprint_type_id` (`blueprint_type_id`),
  KEY `blueprint_id` (`blueprint_id`),
  KEY `blueprint_location_id` (`blueprint_location_id`),
  KEY `output_location_id` (`output_location_id`),
  KEY `product_type_id` (`product_type_id`),
  KEY `status` (`status`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`),
  KEY `completed_date` (`completed_date`),
  KEY `completed_character_id` (`completed_character_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
