---
mail_lists: 'char/mailinglists.xml.aspx'
mail_messages: 'char/MailMessages.xml.aspx'
mail_bodies: 'char/MailBodies.xml.aspx'
contact_list: 'char/ContactList.xml.aspx'
wallet_transactions: 'char/WalletTransactions.xml.aspx'
wallet_journal: 'char/WalletJournal.xml.aspx'
character_sheet: 'char/CharacterSheet.xml.aspx'
asset_list: 'char/AssetList.xml.aspx'
account_status: 'account/AccountStatus.xml.aspx'
api_key_info: 'account/ApiKeyInfo.xml.aspx'
character_name: 'eve/CharacterName.xml.aspx'
character_info: 'eve/CharacterInfo.xml.aspx'
contracts: 'char/Contracts.xml.aspx'
contract_items: 'char/ContractItems.xml.aspx'
skill_in_training: 'char/SkillInTraining.xml.aspx'
